# -*- coding: utf-8 -*-
"""1.Listas enlazadas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JLtTFwwRrkD5DWQGepIiA91NJEYZDMMX

## **Listas Enlazadas**
**Definición de la clase Estudiante**
"""

class Estudiante:
  def __init__(self, Carnet, Nombre, Edad, Address, Phone, Email, Carrera, Puesto):
    self.Carnet = Carnet
    self.Nombre = Nombre
    self.Edad = Edad
    self.Address = Address
    self.Phone = Phone
    self.Email = Email
    self.Carrera = Carrera
    self.Puesto = Puesto

"""**Definición de la clase Nodo**"""

class Nodo:
  def __init__(self, Estudiante = None, Siguiente = None):
    self.Estudiante = Estudiante
    self.Siguiente = Siguiente

"""**Definición de la clase Lista Enlazada**"""

class lista_enlazada:
  def __init__(self):
    self.Primero = None

  def insertar(self, Estudiante):
    if self.Primero is None:
      self.Primero = Nodo(Estudiante = Estudiante)
      return
    actual = self.Primero
    while actual.Siguiente:
      actual = actual.Siguiente
    actual.Siguiente = Nodo(Estudiante = Estudiante)
  def recorrer(self):
    actual = self.Primero
    while actual != None:
      print(f'Carnet: {actual.Estudiante.Carnet}; Nombre: {actual.Estudiante.Nombre}; Email: {actual.Estudiante.Email} ->')
      actual = actual.Siguiente

  def eliminar(self, Carnet):
    actual = self.Primero
    anterior = None
    while actual and actual.Estudiante.Carnet != Carnet:
      anterior = actual
      actual = actual.Siguiente
    if anterior is None:
      self.Primero = actual.Siguiente
      actual.Siguiente = None
    elif actual:
      anterior.Siguiente = actual.Siguiente
      actual.Siguiente = None

"""**Creación de objetos Estudiante**"""

e1 = Estudiante(201015050, "Gerson Ortiz", 20, "0 calle 18-82 zona 1", 24400101,"gerson.ortiz@gmail.com", "Ing. Sistemas", "Programador Jr.")
e2 = Estudiante(201015060, "Karen Hurtarte", 21, "7 calle 18-82 zona 1", 24400102,"karen.hurtarte@gmail.com", "Ing. Sistemas", "Programador Jr.")
e3 = Estudiante(201015061, "Luis Mendez", 22, "8 calle 18-82 zona 1", 24400101,"luis.mendez@gmail.com", "Ing. Sistemas", "Programador Jr.")

"""**Inserción**"""

lista_e = lista_enlazada()
lista_e.insertar(e1)
lista_e.insertar(e2)
lista_e.insertar(e3)

"""**Recorrer Lista**"""

lista_e.recorrer()

"""**Eliminar un Nodo de la lista**"""

lista_e.eliminar(201015060)
lista_e.recorrer()